from src.Snake import snake
from src.Maps import maps

maper = maps.Map("Map_01")
a = snake.Snake("Snake_01",maper)
print(a.locations)
a.move()
print(a.locations)
a.move()
print(a.locations)
a.move()
print(a.locations)
a.move()
print(a.locations)
a.move()
print(a.locations)
a.move()
print(a.locations)
a.move()
print(a.locations)
a.move()
print(a.locations)
a.move()
print(a.locations)
a.move()
print(a.locations)
